use eframe::egui;
use crate::app::DevToolApp;
use crate::theme::*;

impl DevToolApp {
    /// Project and preflight controls shown from the top-bar check icon.
    ///
    /// This is intentionally narrower than the legacy dashboard: Quick Links
    /// and other extras belong in their own sheet, while these controls answer
    /// one question — is the selected project ready to package?
    pub fn show_project_checks_sheet(&mut self, ui: &mut egui::Ui) {
        let have_project = self.project_path.is_some();

        // No title here: the sheet header already says "Project setup &
        // checks", and repeating it as an H1 put the same words on screen
        // twice, one above the other.
        ui.add(egui::Label::new(hint(
            "Change the active project or engine, then review the checks that run before packaging.",
        )).wrap());
        ui.add_space(12.0);

        ui.columns(2, |cols| {
            card().show(&mut cols[0], |ui| {
                ui.set_min_width(ui.available_width());
                ui.label(eyebrow("ACTIVE PROJECT"));
                ui.add_space(8.0);
                self.show_project_path_row(ui);
                ui.add_space(10.0);
                ui.add_enabled_ui(have_project, |ui| {
                    if ui.add_sized(
                        [ui.available_width(), 32.0],
                        primary("Rebuild Visual Studio Files"),
                    ).clicked() {
                        self.open_vs_config();
                    }
                });
            });
            card().show(&mut cols[1], |ui| {
                ui.set_min_width(ui.available_width());
                ui.label(eyebrow("UNREAL ENGINE"));
                ui.add_space(8.0);
                self.show_engine_path_row(ui);
            });
        });

        ui.add_space(10.0);
        card().show(ui, |ui| {
            // Span the row. Without this the card shrank to its content and
            // sat in the left half under two full-width columns, leaving an
            // empty gap beside it.
            ui.set_min_width(ui.available_width());
            ui.label(eyebrow("PREFLIGHT DIAGNOSTICS"));
            ui.add_space(8.0);
            self.show_pc_check_content(ui);
        });

        // Things in the project's own config that break or spoil a package.
        if !self.doctor_items.is_empty() {
            ui.add_space(10.0);
            card().show(ui, |ui| {
                ui.set_min_width(ui.available_width());
                ui.label(eyebrow("PACKAGING READINESS"));
                ui.add_space(4.0);
                ui.label(hint(&format!(
                    "Read from the project's config files, for a {} build.", self.build_target.label())));
                ui.add_space(8.0);
                for item in &self.doctor_items {
                    Self::show_check_item(ui, item);
                }
            });
        }

        ui.add_space(10.0);
        self.show_clean_project(ui);

        ui.add_space(10.0);
        self.show_paste_log_scanner(ui);
    }

    /// Remove Unreal's regenerable folders.
    ///
    /// "Delete Intermediate and Saved, regenerate project files" fixes a large
    /// share of Unreal build failures, and everyone does it by hand in
    /// Explorer. Sizes are shown because the answer to "is it worth it" is
    /// usually several gigabytes, and the delete is two-step because it is not
    /// undoable.
    fn show_clean_project(&mut self, ui: &mut egui::Ui) {
        let mut do_clean = false;
        let mut arm = false;
        let mut disarm = false;

        card().show(ui, |ui| {
            ui.set_min_width(ui.available_width());
            egui::CollapsingHeader::new(eyebrow("CLEAN PROJECT"))
                .id_salt("clean_project")
                .show_background(false)
                .default_open(false)
                .show_unindented(ui, |ui| {
                    ui.add_space(6.0);
                    ui.set_max_width(ui.available_width());
                    ui.add(egui::Label::new(hint(
                        "These folders are regenerated by the engine. Removing them is the standard fix when a build fails for no clear reason.",
                    )).wrap());
                    ui.add_space(10.0);

                    if self.clean_targets.is_empty() {
                        ui.label(hint("Measuring…"));
                        return;
                    }

                    let mut total = 0u64;
                    for (i, t) in self.clean_targets.iter().enumerate() {
                        let mut on = self.clean_selected.get(i).copied().unwrap_or(false);
                        ui.add_enabled_ui(t.exists, |ui| {
                            ui.horizontal(|ui| {
                                if ui.checkbox(&mut on, "").changed()
                                    && let Some(slot) = self.clean_selected.get_mut(i) {
                                        *slot = on;
                                    }
                                ui.vertical(|ui| {
                                    ui.horizontal(|ui| {
                                        ui.label(egui::RichText::new(t.name)
                                            .font(body(12.5))
                                            .color(if t.exists { TEXT } else { FAINT }));
                                        ui.label(numeral(
                                            &if t.exists {
                                                crate::ops::history::format_bytes(t.bytes)
                                            } else { "not present".into() },
                                            11.5,
                                            if t.exists { accent() } else { FAINT }));
                                    });
                                    ui.add(egui::Label::new(hint(t.detail)).wrap());
                                });
                            });
                        });
                        if on && t.exists { total += t.bytes; }
                        ui.add_space(6.0);
                    }

                    ui.add_space(4.0);
                    ui.horizontal(|ui| {
                        if self.clean_confirm {
                            if ui.add_sized([170.0, 30.0],
                                danger(&format!("Delete — {} ", crate::ops::history::format_bytes(total)))).clicked() {
                                do_clean = true;
                            }
                            if ui.add_sized([80.0, 30.0], quiet("Cancel")).clicked() {
                                disarm = true;
                            }
                            ui.label(egui::RichText::new("cannot be undone")
                                .font(body(11.5)).color(AMBER));
                        } else {
                            ui.add_enabled_ui(total > 0, |ui| {
                                if ui.add_sized([170.0, 30.0], ghost(
                                    &format!("Clean — {} ", crate::ops::history::format_bytes(total)))).clicked() {
                                    arm = true;
                                }
                            });
                            if ui.add_sized([90.0, 30.0], quiet("Re-measure")).clicked() {
                                self.refresh_clean_targets();
                            }
                            if self.editor_is_running {
                                ui.label(egui::RichText::new("close the editor first")
                                    .font(body(11.5)).color(AMBER));
                            }
                        }
                    });
                });
        });

        if arm { self.clean_confirm = true; }
        if disarm { self.clean_confirm = false; }
        if do_clean { self.start_clean(); }
    }

    /// Paste-a-log-excerpt scanner — for a log that isn't the most recent one
    /// on disk, which is what the automatic scanner picks up.
    ///
    /// Collapsed by default: it is a troubleshooting tool, not something
    /// needed on every visit, and expanded it costs a three-row textarea plus
    /// two buttons of permanent page space.
    fn show_paste_log_scanner(&mut self, ui: &mut egui::Ui) {
        card().show(ui, |ui| {
            // Span the row: collapsed, a `CollapsingHeader` reports only its
            // own title width and the card shrank to match it.
            ui.set_min_width(ui.available_width());
            // `show_background(false)` strips egui's default header plate so
            // the row reads as a section label in this card rather than as a
            // nested widget with its own surface.
            egui::CollapsingHeader::new(eyebrow("PASTE A LOG TO SCAN"))
                .id_salt("paste_log_scanner")
                .show_background(false)
                .default_open(false)
                .show_unindented(ui, |ui| {
                    ui.add_space(6.0);
                    ui.label(hint(
                        "For a log that isn't the most recent one on disk — paste any excerpt below.",
                    ));
                    ui.add_space(6.0);
                    ui.add(
                        egui::TextEdit::multiline(&mut self.pasted_log_input)
                            .desired_rows(3)
                            .desired_width(ui.available_width())
                            .hint_text("e.g. 'C:\\Program' is not recognized as an internal or external command..."),
                    );
                    ui.add_space(6.0);
                    ui.horizontal(|ui| {
                        let can_scan = !self.pasted_log_input.trim().is_empty();
                        ui.add_enabled_ui(can_scan, |ui| {
                            if ui.add_sized([120.0, 28.0], primary("Analyze")).clicked() {
                                self.scan_pasted_log();
                            }
                        });
                        if !self.pasted_log_diagnosis.is_empty()
                            && ui.add_sized([80.0, 28.0], ghost("Clear")).clicked() {
                                self.pasted_log_input.clear();
                                self.pasted_log_diagnosis.clear();
                            }
                    });

                    if !self.pasted_log_diagnosis.is_empty() {
                        ui.add_space(8.0);
                        for d in &self.pasted_log_diagnosis {
                            callout(AMBER).show(ui, |ui| {
                                ui.label(egui::RichText::new(&d.matched).size(11.5).color(AMBER).strong());
                                ui.add_space(4.0);
                                ui.label(egui::RichText::new(&d.explanation).size(10.5).color(SOFT));
                                ui.add_space(4.0);
                                ui.label(egui::RichText::new(format!("Fix: {}", d.fix)).size(10.5).color(accent()));
                            });
                            ui.add_space(6.0);
                        }
                    }
                });
        });
    }
}
