//! Packaging-readiness checks: things in the project's own files that are
//! known to make a packaged build fail, or succeed and then misbehave.
//!
//! Everything here is a plain file read of a handful of small config files —
//! no Unreal, no process, no network — so it is safe to run on the UI thread.
//! A check only reports what it can actually see; anything it cannot read
//! (a config Unreal has not generated yet) is treated as "unknown", never as a
//! failure.

use std::path::{Path, PathBuf};

use crate::ops::preflight::{CheckItem, CheckStatus};
use crate::types::BuildTarget;

fn item(status: CheckStatus, label: &str, detail: impl Into<String>) -> CheckItem {
    CheckItem { status, label: label.into(), detail: detail.into() }
}

/// Runs every readiness check for `project` when building for `target`.
pub fn check_project(project: &Path, target: BuildTarget) -> Vec<CheckItem> {
    let Some(dir) = project.parent() else { return Vec::new() };
    let mut out = Vec::new();

    // The project file itself.
    let descriptor = std::fs::read_to_string(project)
        .ok()
        .and_then(|t| serde_json::from_str::<serde_json::Value>(&t).ok());
    let Some(desc) = descriptor else {
        out.push(item(CheckStatus::Fail, "Project file",
            "The .uproject could not be read as JSON. Unreal will not open it either."));
        return out;
    };

    // Code or Blueprint-only.
    let has_modules = desc.get("Modules").and_then(|m| m.as_array()).is_some_and(|m| !m.is_empty());
    if has_modules {
        if dir.join("Source").is_dir() {
            out.push(item(CheckStatus::Ok, "C++ project", "Source folder present."));
            if !dir.join("Binaries").is_dir() {
                out.push(item(CheckStatus::Ok, "Not compiled yet",
                    "There is no Binaries folder, so the first build compiles everything and will be slow."));
            }
        } else {
            out.push(item(CheckStatus::Fail, "Source folder missing",
                "The project lists code modules but has no Source folder — packaging cannot compile it."));
        }
    } else {
        out.push(item(CheckStatus::Ok, "Blueprint-only project", "Nothing to compile."));
    }

    // Default map: without one a packaged game starts in an empty world.
    let engine_ini = std::fs::read_to_string(dir.join("Config").join("DefaultEngine.ini")).ok();
    match engine_ini.as_deref().and_then(|t| ini_value(t, "/Script/EngineSettings.GameMapsSettings", "GameDefaultMap")) {
        Some(map) if !map.is_empty() => {
            match map_file(dir, &map) {
                Some(path) if path.is_file() =>
                    out.push(item(CheckStatus::Ok, "Default map", map)),
                Some(_) => out.push(item(CheckStatus::Warn, "Default map not found",
                    format!("{map} is set as the game's start map but no matching file is under Content."))),
                None => out.push(item(CheckStatus::Ok, "Default map", map)),
            }
        }
        _ if engine_ini.is_none() => {} // no config yet: unknown, not a failure
        _ => out.push(item(CheckStatus::Warn, "No default map set",
            "GameDefaultMap is not set in DefaultEngine.ini. A packaged game will open to an empty world. \
             Set it in Project Settings → Maps & Modes.")),
    }

    // Android needs a real package name; the template default is rejected by
    // the Play Store and by some device installers.
    if target == BuildTarget::Android {
        let game_ini = std::fs::read_to_string(dir.join("Config").join("DefaultEngine.ini")).ok();
        let name = game_ini.as_deref()
            .and_then(|t| ini_value(t, "/Script/AndroidRuntimeSettings.AndroidRuntimeSettings", "PackageName"));
        match name {
            Some(n) if !n.contains("YourCompany") && !n.trim().is_empty() =>
                out.push(item(CheckStatus::Ok, "Android package name", n)),
            Some(n) => out.push(item(CheckStatus::Warn, "Android package name is the template default",
                format!("{n} — set your own in Project Settings → Platforms → Android."))),
            None => out.push(item(CheckStatus::Warn, "Android package name not set",
                "The default com.YourCompany.[PROJECT] is used. Set your own in Project Settings → Platforms → Android.")),
        }
    }

    // Source control: generated folders that must not be committed.
    if let Some((_, missing, exists)) = gitignore_gaps(dir) {
        if missing.is_empty() {
            out.push(item(CheckStatus::Ok, ".gitignore", "Generated folders are ignored."));
        } else {
            out.push(item(CheckStatus::Warn, ".gitignore", format!(
                "{} not ignored: {}. They are regenerated by Unreal and can be gigabytes.",
                if exists { "These are" } else { "There is no .gitignore, so these are" },
                missing.join(", "))));
        }
    }

    out
}

/// Folders Unreal generates that a repository should never contain.
const GENERATED: [&str; 4] = ["Intermediate", "Saved", "DerivedDataCache", "Binaries"];

/// For a project inside a git repository: its `.gitignore`, the generated
/// folders it fails to ignore, and whether the file exists. `None` when the
/// project is not under git at all (then there is nothing to check).
fn gitignore_gaps(project_dir: &Path) -> Option<(PathBuf, Vec<&'static str>, bool)> {
    // The repository root may be the project folder or a parent of it.
    let in_repo = project_dir.ancestors().take(4).any(|d| d.join(".git").exists());
    if !in_repo { return None; }
    let file = project_dir.join(".gitignore");
    let text = std::fs::read_to_string(&file).ok();
    let ignored = |name: &str| text.as_deref().is_some_and(|t| t.lines().any(|l| {
        let l = l.trim();
        !l.starts_with('#') && l.trim_start_matches('/').trim_end_matches(['/', '*']) == name
    }));
    let missing = GENERATED.into_iter().filter(|n| !ignored(n)).collect();
    Some((file.clone(), missing, text.is_some()))
}

// ── Fixes ────────────────────────────────────────────────────────────────────

/// A change the app can make for the person, offered next to the check that
/// found the problem. Nothing is applied without a click, and every file it
/// changes is backed up first.
#[derive(Clone, PartialEq, Debug)]
pub enum FixKind {
    /// Set `GameDefaultMap` in `Config/DefaultEngine.ini` to this asset path.
    SetDefaultMap(String),
    /// Append these folders to the project's `.gitignore`.
    IgnoreFolders(Vec<&'static str>),
}

#[derive(Clone, Debug)]
pub struct Fix {
    /// The label of the check this belongs to.
    pub for_label: &'static str,
    pub button:    String,
    /// One line saying exactly what will change.
    pub what:      String,
    pub kind:      FixKind,
}

/// The fixes that apply to the project as it is now.
pub fn fixes(project: &Path) -> Vec<Fix> {
    let Some(dir) = project.parent() else { return Vec::new() };
    let mut out = Vec::new();

    let engine_ini = std::fs::read_to_string(dir.join("Config").join("DefaultEngine.ini")).ok();
    let has_map = engine_ini.as_deref()
        .and_then(|t| ini_value(t, "/Script/EngineSettings.GameMapsSettings", "GameDefaultMap"))
        .is_some_and(|m| !m.is_empty());
    if !has_map && let Some(map) = pick_default_map(&find_maps(dir)) {
        out.push(Fix {
            for_label: "No default map set",
            button: "Set it".into(),
            what: format!("Sets GameDefaultMap={map} in Config/DefaultEngine.ini"),
            kind: FixKind::SetDefaultMap(map),
        });
    }

    if let Some((_, missing, _)) = gitignore_gaps(dir) && !missing.is_empty() {
        out.push(Fix {
            for_label: ".gitignore",
            button: "Add them".into(),
            what: format!("Appends {} to .gitignore", missing.join(", ")),
            kind: FixKind::IgnoreFolders(missing),
        });
    }
    out
}

/// Applies a fix. Returns a sentence describing what was done.
pub fn apply(project: &Path, kind: &FixKind) -> Result<String, String> {
    let dir = project.parent().ok_or("The project has no folder.")?;
    match kind {
        FixKind::SetDefaultMap(map) => {
            let file = dir.join("Config").join("DefaultEngine.ini");
            let text = std::fs::read_to_string(&file).unwrap_or_default();
            backup_once(&file)?;
            let _ = std::fs::create_dir_all(dir.join("Config"));
            let edited = ini_set(&text, "/Script/EngineSettings.GameMapsSettings", "GameDefaultMap", map);
            std::fs::write(&file, edited).map_err(|e| format!("Could not write DefaultEngine.ini: {e}"))?;
            Ok(format!("Set the default map to {map}."))
        }
        FixKind::IgnoreFolders(names) => {
            let file = dir.join(".gitignore");
            let mut text = std::fs::read_to_string(&file).unwrap_or_default();
            backup_once(&file)?;
            let nl = if text.contains("\r\n") { "\r\n" } else { "\n" };
            if !text.is_empty() && !text.ends_with('\n') { text.push_str(nl); }
            text.push_str(&format!("{nl}# Unreal Engine (added by Unreal DevTool){nl}"));
            for n in names { text.push_str(&format!("{n}/{nl}")); }
            std::fs::write(&file, text).map_err(|e| format!("Could not write .gitignore: {e}"))?;
            Ok(format!("Added {} to .gitignore.", names.join(", ")))
        }
    }
}

/// Copies `file` to `<file>.devtool-backup` unless that already exists or the
/// file is not there yet.
fn backup_once(file: &Path) -> Result<(), String> {
    if !file.is_file() { return Ok(()); }
    let mut b = file.as_os_str().to_os_string();
    b.push(".devtool-backup");
    let b = PathBuf::from(b);
    if b.exists() { return Ok(()); }
    std::fs::copy(file, &b).map(|_| ()).map_err(|e| format!("Could not make a backup: {e}"))
}

/// Sets `key=value` inside `[section]` of an `.ini`, keeping everything else —
/// comments, order, line endings — as it was. Adds the section if it is missing.
pub fn ini_set(text: &str, section: &str, key: &str, value: &str) -> String {
    let nl = if text.contains("\r\n") { "\r\n" } else { "\n" };
    let mut lines: Vec<String> = text.lines().map(str::to_string).collect();
    let header = |l: &str| l.trim().strip_prefix('[').and_then(|x| x.strip_suffix(']')).map(str::to_string);
    let start = lines.iter().position(|l| header(l).is_some_and(|n| n.eq_ignore_ascii_case(section)));
    let new_line = format!("{key}={value}");

    match start {
        Some(i) => {
            let end = lines.iter().skip(i + 1).position(|l| header(l).is_some()).map(|p| p + i + 1).unwrap_or(lines.len());
            let existing = (i + 1..end).find(|&j| {
                lines[j].split_once('=').is_some_and(|(k, _)|
                    k.trim().trim_start_matches(['+', '-', '.', '!']).eq_ignore_ascii_case(key))
            });
            match existing {
                Some(j) => lines[j] = new_line,
                None => {
                    // After the section's last real line, before any blank tail.
                    let mut at = end;
                    while at > i + 1 && lines[at - 1].trim().is_empty() { at -= 1; }
                    lines.insert(at, new_line);
                }
            }
        }
        None => {
            if lines.last().is_some_and(|l| !l.trim().is_empty()) { lines.push(String::new()); }
            lines.push(format!("[{section}]"));
            lines.push(new_line);
        }
    }
    let mut out = lines.join(nl);
    out.push_str(nl);
    out
}

/// Map assets under `Content`, as `/Game/…/Name.Name` paths.
pub fn find_maps(project_dir: &Path) -> Vec<String> {
    let content = project_dir.join("Content");
    let mut out = Vec::new();
    let mut stack = vec![content.clone()];
    let mut seen = 0u32;
    while let Some(d) = stack.pop() {
        let Ok(rd) = std::fs::read_dir(&d) else { continue };
        for e in rd.flatten() {
            seen += 1;
            if seen > 20_000 { return out; }
            let p = e.path();
            if p.is_dir() { stack.push(p); continue; }
            if p.extension().is_some_and(|x| x.eq_ignore_ascii_case("umap"))
                && let Ok(rel) = p.strip_prefix(&content) {
                let rel = rel.with_extension("").to_string_lossy().replace('\\', "/");
                let name = rel.rsplit('/').next().unwrap_or(&rel).to_string();
                out.push(format!("/Game/{rel}.{name}"));
            }
        }
    }
    out.sort();
    out
}

/// The map most likely meant as the game's start: the only one, or the first
/// with a name that says so. `None` when it would be a guess.
pub fn pick_default_map(maps: &[String]) -> Option<String> {
    if maps.len() == 1 { return maps.first().cloned(); }
    const HINTS: [&str; 7] = ["mainmenu", "menu", "main", "startup", "start", "entry", "lobby"];
    for hint in HINTS {
        if let Some(m) = maps.iter().find(|m| {
            m.rsplit('.').next().unwrap_or("").to_ascii_lowercase() == hint
        }) { return Some(m.clone()); }
    }
    None
}

/// The value of `key` inside `[section]` of an Unreal `.ini`, ignoring
/// comments, quotes and the `+`/`-`/`!` list prefixes.
pub fn ini_value(text: &str, section: &str, key: &str) -> Option<String> {
    let mut in_section = false;
    let mut found = None;
    for raw in text.lines() {
        let line = raw.trim();
        if line.starts_with(';') || line.is_empty() { continue; }
        if let Some(name) = line.strip_prefix('[').and_then(|l| l.strip_suffix(']')) {
            in_section = name.eq_ignore_ascii_case(section);
            continue;
        }
        if !in_section { continue; }
        let Some((k, v)) = line.split_once('=') else { continue };
        let k = k.trim().trim_start_matches(['+', '-', '.', '!']);
        if k.eq_ignore_ascii_case(key) {
            // The last assignment wins, as it does in Unreal.
            found = Some(v.trim().trim_matches('"').to_string());
        }
    }
    found
}

/// `/Game/Maps/Main.Main` → `<project>/Content/Maps/Main.umap`.
fn map_file(project_dir: &Path, asset_path: &str) -> Option<std::path::PathBuf> {
    let rest = asset_path.strip_prefix("/Game/")?;
    let no_object = rest.split('.').next()?;
    Some(project_dir.join("Content").join(format!("{no_object}.umap")))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn project(name: &str, uproject: &str) -> (std::path::PathBuf, std::path::PathBuf) {
        let root = std::env::temp_dir().join(format!("udt-doctor-{name}-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&root);
        std::fs::create_dir_all(root.join("Config")).unwrap();
        std::fs::create_dir_all(root.join("Content/Maps")).unwrap();
        let file = root.join("Game.uproject");
        std::fs::write(&file, uproject).unwrap();
        (root, file)
    }

    fn statuses(items: &[CheckItem]) -> Vec<(&str, bool)> {
        items.iter().map(|i| (i.label.as_str(), matches!(i.status, CheckStatus::Ok))).collect()
    }

    #[test]
    fn ini_lookup_handles_sections_prefixes_and_last_wins() {
        let text = "; c\n[A]\nKey=1\n[/Script/X.Y]\n+Foo=bar\nKey=\"old\"\nKey=new\n[B]\nKey=other\n";
        assert_eq!(ini_value(text, "/Script/X.Y", "Key").as_deref(), Some("new"));
        assert_eq!(ini_value(text, "/Script/X.Y", "Foo").as_deref(), Some("bar"));
        assert_eq!(ini_value(text, "/script/x.y", "key").as_deref(), Some("new"), "case-insensitive");
        assert_eq!(ini_value(text, "Nope", "Key"), None);
    }

    #[test]
    fn a_blueprint_project_without_a_default_map_is_warned() {
        let (root, file) = project("bp", r#"{"FileVersion":3,"EngineAssociation":"5.7"}"#);
        std::fs::write(root.join("Config/DefaultEngine.ini"), "[/Script/EngineSettings.GameMapsSettings]\n").unwrap();
        let out = check_project(&file, BuildTarget::Win64);
        assert!(out.iter().any(|i| i.label == "Blueprint-only project"));
        assert!(out.iter().any(|i| i.label == "No default map set" && matches!(i.status, CheckStatus::Warn)));
        std::fs::remove_dir_all(root).unwrap();
    }

    #[test]
    fn a_default_map_is_resolved_against_content() {
        let (root, file) = project("map", r#"{"Modules":[]}"#);
        std::fs::write(root.join("Config/DefaultEngine.ini"),
            "[/Script/EngineSettings.GameMapsSettings]\nGameDefaultMap=/Game/Maps/Main.Main\n").unwrap();
        assert!(check_project(&file, BuildTarget::Win64).iter()
            .any(|i| i.label == "Default map not found"));
        std::fs::write(root.join("Content/Maps/Main.umap"), "x").unwrap();
        let ok = check_project(&file, BuildTarget::Win64);
        assert!(ok.iter().any(|i| i.label == "Default map" && matches!(i.status, CheckStatus::Ok)));
        std::fs::remove_dir_all(root).unwrap();
    }

    #[test]
    fn code_projects_need_a_source_folder_and_android_needs_a_package_name() {
        let (root, file) = project("cpp", r#"{"Modules":[{"Name":"Game"}]}"#);
        let out = check_project(&file, BuildTarget::Win64);
        assert!(out.iter().any(|i| i.label == "Source folder missing" && matches!(i.status, CheckStatus::Fail)));

        std::fs::create_dir_all(root.join("Source")).unwrap();
        let out = check_project(&file, BuildTarget::Win64);
        assert!(out.iter().any(|i| i.label == "Not compiled yet"));
        assert!(!out.iter().any(|i| i.label.starts_with("Android")), "only when building for Android");

        std::fs::write(root.join("Config/DefaultEngine.ini"),
            "[/Script/AndroidRuntimeSettings.AndroidRuntimeSettings]\nPackageName=com.YourCompany.[PROJECT]\n").unwrap();
        let out = check_project(&file, BuildTarget::Android);
        assert!(out.iter().any(|i| i.label.contains("template default")));
        std::fs::write(root.join("Config/DefaultEngine.ini"),
            "[/Script/AndroidRuntimeSettings.AndroidRuntimeSettings]\nPackageName=com.acme.fish\n").unwrap();
        let out = check_project(&file, BuildTarget::Android);
        assert!(statuses(&out).contains(&("Android package name", true)));
        std::fs::remove_dir_all(root).unwrap();
    }

    #[test]
    fn a_broken_project_file_is_a_failure_and_stops_early() {
        let (root, file) = project("bad", "{ not json");
        let out = check_project(&file, BuildTarget::Win64);
        assert_eq!(out.len(), 1);
        assert!(matches!(out[0].status, CheckStatus::Fail));
        std::fs::remove_dir_all(root).unwrap();
    }

    #[test]
    fn ini_set_edits_in_place_or_adds_the_section() {
        let text = "; header\n[/Script/A.B]\nOther=1\nGameDefaultMap=/Game/Old.Old\n\n[Z]\nK=v\n";
        let out = ini_set(text, "/Script/A.B", "GameDefaultMap", "/Game/New.New");
        assert!(out.contains("GameDefaultMap=/Game/New.New") && !out.contains("Old.Old"));
        assert!(out.contains("; header") && out.contains("[Z]\nK=v"), "the rest is untouched: {out}");

        // Key missing from an existing section: inserted inside it, not after the next one.
        let out = ini_set("[S]\nA=1\n\n[T]\nB=2\n", "S", "New", "9");
        assert!(out.find("New=9").unwrap() < out.find("[T]").unwrap(), "{out}");
        // Section missing: appended.
        let out = ini_set("[S]\nA=1\n", "Q", "K", "V");
        assert!(out.ends_with("[Q]\nK=V\n"), "{out}");
        // Windows line endings are kept.
        assert!(ini_set("[S]\r\nA=1\r\n", "S", "A", "2").contains("A=2\r\n"));
    }

    #[test]
    fn a_default_map_is_only_guessed_when_the_name_says_so() {
        let m = |n: &str| format!("/Game/Maps/{n}.{n}");
        assert_eq!(pick_default_map(&[m("Only")]), Some(m("Only")));
        assert_eq!(pick_default_map(&[m("Arena"), m("MainMenu"), m("Test")]), Some(m("MainMenu")));
        assert_eq!(pick_default_map(&[m("Arena"), m("Test")]), None, "no basis to choose");
        assert_eq!(pick_default_map(&[]), None);
    }

    #[test]
    fn the_default_map_fix_is_offered_and_applied_with_a_backup() {
        let (root, file) = project("fixmap", r#"{"Modules":[]}"#);
        std::fs::write(root.join("Content/Maps/Level1.umap"), "x").unwrap();
        std::fs::write(root.join("Config/DefaultEngine.ini"), "[/Script/EngineSettings.GameMapsSettings]\n").unwrap();
        let fix = fixes(&file).into_iter().find(|f| f.for_label == "No default map set").expect("a fix");
        assert_eq!(fix.kind, FixKind::SetDefaultMap("/Game/Maps/Level1.Level1".into()));

        apply(&file, &fix.kind).unwrap();
        let ini = std::fs::read_to_string(root.join("Config/DefaultEngine.ini")).unwrap();
        assert!(ini.contains("GameDefaultMap=/Game/Maps/Level1.Level1"));
        assert!(root.join("Config/DefaultEngine.ini.devtool-backup").is_file());
        assert!(check_project(&file, BuildTarget::Win64).iter().any(|i| i.label == "Default map"),
            "the problem is gone after the fix");
        assert!(fixes(&file).iter().all(|f| f.for_label != "No default map set"));
        std::fs::remove_dir_all(root).unwrap();
    }

    #[test]
    fn gitignore_gaps_are_found_and_filled_only_inside_a_repository() {
        let (root, file) = project("ignore", r#"{"Modules":[]}"#);
        let outside_repo = !root.ancestors().take(4).any(|d| d.join(".git").exists());
        if outside_repo {
            assert!(gitignore_gaps(&root).is_none(), "not a repository, nothing to check");
        }
        std::fs::create_dir_all(root.join(".git")).unwrap();
        std::fs::write(root.join(".gitignore"), "# c\n/Intermediate/\nSaved\n").unwrap();

        let (_, missing, exists) = gitignore_gaps(&root).unwrap();
        assert!(exists);
        assert_eq!(missing, vec!["DerivedDataCache", "Binaries"]);
        let fix = fixes(&file).into_iter().find(|f| f.for_label == ".gitignore").unwrap();
        apply(&file, &fix.kind).unwrap();
        assert!(gitignore_gaps(&root).unwrap().1.is_empty());
        assert!(root.join(".gitignore.devtool-backup").is_file());
        assert!(check_project(&file, BuildTarget::Win64).iter()
            .any(|i| i.label == ".gitignore" && matches!(i.status, CheckStatus::Ok)));
        std::fs::remove_dir_all(root).unwrap();
    }
}
